name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}-latest
    name: CI (${{ matrix.cc }} on ${{ matrix.os }})
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        cc: ["gcc", "clang"]
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - name: apt-get install packages
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt-get update -qq
        sudo apt-get install --no-install-recommends -y ${{ matrix.cc }} git libyaml-dev make valgrind
    - name: brew install deps
      if: matrix.os == 'macos'
      run: brew update && brew install libyaml
    - name: build
      run: make
    - name: test
      run: make test
    - name: valgrind test (gcc)
      if: matrix.os != 'macos' && matrix.cc == 'gcc'
      run: make valgrind-quiet
    - name: valgrind test (clang)
      if: matrix.os != 'macos' && matrix.cc == 'clang'
      run: CFLAGS=-gdwarf-4 make -B valgrind-quiet
    - name: sanitize test
      if: matrix.os != 'macos'
      run: make VARIANT=san test
